version: 2.1
orbs:
   aws-cli: circleci/aws-cli@2.0.3
   serverless-framework: circleci/serverless-framework@1.0.1
jobs:
  deploy:
    docker:
      - image: cimg/node:14.17.5
    steps:
      - checkout
      - run: node --version
      - run:
          name: sls deploy
          command: |
            npm install
            sudo npm install -g serverless
            serverless deploy --stage dev-ap
        
      
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          name: deploy
          context: contextTest
          filters:
            branches:
              only:
                - release